{
  "openapi": "3.0.0",
  "info": {
    "title": "REST API",
    "version": "1.0.0",
    "description": "Documentation for all sample project REST API endpoints."
  },
  "tags": [
    {
      "name": "Endpoints"
    }
  ],
  "servers": [
    {
      "url": "127.0.0.1"
    }
  ],
  "paths": {
    "/api/register": {
      "parameters": [],
      "post": {
        "summary": "Register a New User",
        "tags": [
            "Endpoints"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "required": false,
            "example": "Test User",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "required": false,
            "example": "test@test.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": false,
            "example": "test1234",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Token Success Response"
                },
                "example": {
                  "success": true,
                  "message": "User registered successfully.",
                  "token": "4|Vhwa0cL8JkL9k28h4gW9SEKUSZUaePLpNtuV6Vw447f2c49c",
                  "user": {
                    "name": "Test User",
                    "email": "test321@test.com",
                    "updated_at": "2025-10-05T01:56:43.000000Z",
                    "created_at": "2025-10-05T01:56:43.000000Z",
                    "id": 14
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. User not registered.",
                  "error": {
                    "email": [
                      "The email has already been taken."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/New User"
              },
              "example": {
                "name": "Test User",
                "email": "test@test.com",
                "password": "test1234"
              }
            }
          }
        }
      }
    },
    "/api/token/create": {
      "parameters": [],
      "post": {
        "summary": "Create a New API Token",
        "tags": [
          "Endpoints"
        ],
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": false,
            "example": "test@example.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": false,
            "example": "test1234",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Token Success Response"
                },
                "example": {
                  "success": true,
                  "message": "Token created successfully.",
                  "token": "4|Vhwa0cL8JkL9k28h4gW9SEKUSZUaePLpNtuV6Vw447f2c49c",
                  "user": {
                    "id": 14,
                    "name": "Test User",
                    "email": "test321@test.com",
                    "updated_at": "2025-10-05T01:56:43.000000Z",
                    "created_at": "2025-10-05T01:56:43.000000Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. Token not created.",
                  "error": "Unauthorized"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Test User",
                "email": "test@test.com"
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "parameters": [],
      "post": {
        "summary": "Login",
        "tags": [
          "Endpoints"
        ],
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": false,
            "example": "test@example.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": false,
            "example": "test1234",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Token Success Response"
                },
                "example": {
                  "success": true,
                  "message": "Login successful.",
                  "token": "9|uW0ExJwbZdEee1cSn59jPpdz4vdwRvpPmrXvZUL6cc0b0359",
                  "user": {
                    "id": 1,
                    "name": "Test User",
                    "email": "test@example.com",
                    "created_at": "2025-06-10T19:42:03.000000Z",
                    "updated_at": "2025-06-10T19:42:03.000000Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. Login unsuccessful.",
                  "error": "Unauthorized"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/logout": {
      "parameters": [],
      "post": {
        "summary": "Logout",
        "tags": [
          "Endpoints"
        ],
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": false,
            "example": "test@example.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": false,
            "example": "test1234",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Simple Success Response"
                },
                "example": {
                  "success": true,
                  "message": "Logout successful."
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. Logout unsuccessful.",
                  "error": "Unauthorized"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user": {
      "parameters": [],
      "get": {
        "summary": "Get Current User",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Success Response"
                },
                "example": {
                  "success": true,
                  "message": "User found successfully.",
                  "user": {
                    "id": 1,
                    "name": "Test User",
                    "email": "test@example.com",
                    "created_at": "2025-06-10T19:42:03.000000Z",
                    "updated_at": "2025-06-10T19:42:03.000000Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. User not found.",
                  "user": null
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Patch Current User",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "example": "Post Test User",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "required": false,
            "example": "test@test.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": false,
            "example": "test1234",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Success Response"
                },
                "example": {
                  "success": true,
                  "message": "User updated successfully.",
                  "user": {
                    "id": 1,
                    "name": "TESTABLE",
                    "email": "test@example.com",
                    "created_at": "2025-06-10T19:42:03.000000Z",
                    "updated_at": "2025-10-05T23:45:49.000000Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. User not updated.",
                  "user": null
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/New User"
              },
              "example": {
                "name": "TESTABLE"
              }
            }
          }
        }
      },
      "put": {
        "summary": "Put Current User",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "example": "Post Test User",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "required": false,
            "example": "test@test.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": false,
            "example": "test1234",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Success Response"
                },
                "example": {
                  "success": true,
                  "message": "User updated successfully.",
                  "user": {
                    "id": 1,
                    "name": "TESTABLE",
                    "email": "test@example.com",
                    "created_at": "2025-06-10T19:42:03.000000Z",
                    "updated_at": "2025-10-05T23:45:49.000000Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. User not updated.",
                  "user": null
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/New User"
              },
              "example": {
                "name": "TESTABLE"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Current User",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "schema": {
            "$ref": "#/components/responses/Simple Success Response"
          },
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Simple Success Response"
                },
                "example": {
                  "success": true,
                  "message": "User deleted successfully."
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Simple Success Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. User not deleted."
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      }
    },
    "/api/record": {
      "parameters": [],
      "get": {
        "summary": "Get Records",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Records Success Response"
                },
                "example": {
                  "success": true,
                  "message": "Records retrieved successfully.",
                  "records": [
                    {
                      "id": 2,
                      "string": "Totam quod velit et. Id temporibus magnam enim sed non temporibus distinctio. Ut soluta magnam impedit nisi. Quis autem qui error molestiae omnis dolores. Explicabo et nisi iure vero aliquam iure. Nihil autem quo consequatur animi iste perspiciatis.",
                      "text": "Voluptatibus et qui ducimus consequuntur impedit sit. Ab laborum fugit minima sed ut. Sunt sed quia corrupti porro mollitia. Voluptas corporis est autem voluptatibus illo beatae maxime. Neque qui sequi blanditiis et. Unde velit in aliquam et delectus qui et. Nihil quia numquam est velit quidem sunt reprehenderit. Unde non impedit velit alias aliquam impedit et. Molestiae et laboriosam sit quasi ea et dolores. Corporis sint eligendi ab numquam quia eaque labore. Sequi dolor in sequi blanditiis ipsam velit necessitatibus occaecati. Doloremque doloribus quasi accusantium blanditiis dolores. Rerum nemo aut omnis id autem perspiciatis et. Commodi maxime expedita quia eos iste qui. Eum provident qui dolores aut iure ex. Nemo optio sequi laudantium voluptatum nesciunt sint tempora voluptas. Debitis sit ut autem eum. Ad quam enim ex id. Aperiam similique enim repellat quam quae. Officia officia asperiores accusantium expedita. Voluptatem sit recusandae est alias nam qui et beatae.",
                      "json": null,
                      "boolean": true,
                      "integer": 1,
                      "float": 53.5,
                      "deleted_at": null,
                      "created_at": "2025-06-10T19:42:04.000000Z",
                      "updated_at": "2025-06-10T19:42:04.000000Z"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Records Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. Records not found.",
                  "records": null
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      },
      "post": {
        "summary": "Add Record",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "string",
            "in": "query",
            "required": false,
            "example": "test",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Record Success Response"
                },
                "example": {
                  "success": true,
                  "message": "Record created successfully.",
                  "record": {
                    "string": "test",
                    "text": null,
                    "json": null,
                    "boolean": false,
                    "integer": 0,
                    "float": 0
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Record Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. Record not created.",
                  "record": null
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      }
    },
    "/api/record/{id}": {
      "parameters": [],
      "get": {
        "summary": "Get Record By ID",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "url",
            "required": false,
            "example": "1",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Records Success Response"
                },
                "example": {
                  "success": true,
                  "message": "Record retrieved successfully.",
                  "record": {
                    "id": 2,
                    "string": "Totam quod velit et. Id temporibus magnam enim sed non temporibus distinctio. Ut soluta magnam impedit nisi. Quis autem qui error molestiae omnis dolores. Explicabo et nisi iure vero aliquam iure. Nihil autem quo consequatur animi iste perspiciatis.",
                    "text": "Voluptatibus et qui ducimus consequuntur impedit sit. Ab laborum fugit minima sed ut. Sunt sed quia corrupti porro mollitia. Voluptas corporis est autem voluptatibus illo beatae maxime. Neque qui sequi blanditiis et. Unde velit in aliquam et delectus qui et. Nihil quia numquam est velit quidem sunt reprehenderit. Unde non impedit velit alias aliquam impedit et. Molestiae et laboriosam sit quasi ea et dolores. Corporis sint eligendi ab numquam quia eaque labore. Sequi dolor in sequi blanditiis ipsam velit necessitatibus occaecati. Doloremque doloribus quasi accusantium blanditiis dolores. Rerum nemo aut omnis id autem perspiciatis et. Commodi maxime expedita quia eos iste qui. Eum provident qui dolores aut iure ex. Nemo optio sequi laudantium voluptatum nesciunt sint tempora voluptas. Debitis sit ut autem eum. Ad quam enim ex id. Aperiam similique enim repellat quam quae. Officia officia asperiores accusantium expedita. Voluptatem sit recusandae est alias nam qui et beatae.",
                    "json": null,
                    "boolean": true,
                    "integer": 1,
                    "float": 53.5,
                    "deleted_at": null,
                    "created_at": "2025-06-10T19:42:04.000000Z",
                    "updated_at": "2025-06-10T19:42:04.000000Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "An unsuccessful response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Record Error Response"
                },
                "example": {
                  "success": false,
                  "message": "Task failed. Record not found.",
                  "record": null
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      },
      "put": {
        "summary": "Put Record By ID",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "string",
            "in": "query",
            "required": false,
            "example": "test put string",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {},
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Patch Record By ID",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "string",
            "in": "query",
            "required": false,
            "example": "test patch string",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {},
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Record By ID",
        "tags": [
          "Endpoints"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": false,
            "example": "1|KfScfXlgJIOpTh9TMiZNUc4nmkt2oEgFFVyYkxIHe900f87c",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {},
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Enter your Bearer Token."
      }
    },
    "schemas": {
      "New User": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "New Record": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "text": {
            "type": "text"
          },
          "json": {
            "type": "string"
          },
          "boolean": {
            "type": "boolean"
          },
          "integer": {
            "type": "integer"
          },
          "float": {
            "type": "float"
          }
        }
      },
      "Record": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "text": {
            "type": "text"
          },
          "json": {
            "type": "string"
          },
          "boolean": {
            "type": "boolean"
          },
          "integer": {
            "type": "integer"
          },
          "float": {
            "type": "float"
          },
          "deleted_at": {
            "type": "datetime"
          },
          "created_at": {
            "type": "datetime"
          },
          "updated_at": {
            "type": "datetime"
          }
        }
      }
    },
    "parameters": {

    },
    "examples": {

    },
    "responses": {
      "Simple Success Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "User Token Success Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "token": {
            "type": "string"
          },
          "user": {
            "$ref": "#/components/schemas/User"
          }
        }
      },
      "User Success Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "user": {
            "$ref": "#/components/schemas/User"
          }
        }
      },
      "Record Success Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "record": {
            "$ref": "#/components/schemas/New Record"
          }
        }
      },
      "Records Success Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "records": {
            "$ref": "#/components/schemas/Record"
          }
        }
      },
      "Error Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "error": {
            "type": "object"
          }
        }
      },
      "User Error Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "user": {
            "type": "null"
          }
        }
      },
      "Record Error Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "record": {
            "type": "null"
          }
        }
      },
      "Records Error Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "records": {
            "type": "null"
          }
        }
      }
    }
  }
}